# require: rubocop-rspec
# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - vendor/**/*

Documentation:
  Enabled: false

Rails:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/Tab:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
